// Hawara Advanced Contracting Co. — Project history data
// Values in JOD (Jordanian Dinar)
const PROJECTS = [
  { n: 1, project: "Factory of Jordan Bahrain Paper Industries, Amman", client: "Jordan Bahrain Paper Industries", role: "Main Contractor", date: "Oct 2008", year: 2008, desc: "Construction & Finishing", value: 2554549 },
  { n: 2, project: "Engineering College Building, Zarqa", client: "Al Zarqa Education Company", role: "Main Contractor", date: "Oct 2009", year: 2009, desc: "Construction & Finishing", value: 3636292 },
  { n: 3, project: "Amman Arab University, Amman", client: "Company of Management & Developer Research and Education", role: "Main Contractor", date: "Jun 2010", year: 2010, desc: "Construction & Finishing", value: 3798169 },
  { n: 4, project: "Irbid City Center, Irbid", client: "Marseilles Real Estate Investment", role: "Main Contractor", date: "Jun 2011", year: 2011, desc: "Construction & Finishing", value: 10136000 },
  { n: 5, project: "Press and Media College, Zarqa", client: "AlZarqa Education Company", role: "Main Contractor", date: "Mar 2011", year: 2011, desc: "Construction & Finishing", value: 3026564 },
  { n: 6, project: "Primary School, Zarqa", client: "AlZarqa Education Company", role: "Main Contractor", date: "Sep 2011", year: 2011, desc: "Construction & Finishing", value: 1961968 },
  { n: 7, project: "Girls Secondary School, Zarqa", client: "AlZarqa Education Company", role: "Main Contractor", date: "Sep 2011", year: 2011, desc: "Construction & Finishing", value: 1174745 },
  { n: 8, project: "Boys Secondary School, Zarqa", client: "AlZarqa Education Company", role: "Main Contractor", date: "Sep 2011", year: 2011, desc: "Construction & Finishing", value: 1212288 },
  { n: 9, project: "Sameh Mall Markets, Amman & Irbid", client: "Sameh Mall Group", role: "Main Contractor", date: "Jan 2012", year: 2012, desc: "Construction & Finishing", value: 10862849 },
  { n: 10, project: "Momtalkat Housing Building, Amman", client: "Momtalkat Investment", role: "Main Contractor", date: "Mar 2012", year: 2012, desc: "Construction & Finishing", value: 3732085 },
  { n: 11, project: "Sameh Mall Market, Amman", client: "Sameh Mall Group", role: "Main Contractor", date: "Nov 2013", year: 2013, desc: "Construction & Finishing", value: 619376 },
  { n: 12, project: "Mr. Ahmed Al-Jabouri Complex, Amman – Ras Al Ain", client: "Mr. Ahmed Al-Jabouri", role: "Main Contractor", date: "Mar 2014", year: 2014, desc: "Construction & Finishing", value: 1295066 },
  { n: 13, project: "Sameh Mall Market, Amman – Qawismeh", client: "Sameh Mall Group", role: "Main Contractor", date: "Feb 2015", year: 2015, desc: "Construction & Finishing", value: 811722 },
  { n: 14, project: "Istiklal Mall, Amman – Istiklal Street", client: "Geron Investment", role: "Main Contractor", date: "Feb 2015", year: 2015, desc: "Construction & Finishing", value: 3531599 },
  { n: 15, project: "Huriah Mall, Amman – Huriah Street", client: "San Diego Investments", role: "Main Contractor", date: "Oct 2015", year: 2015, desc: "Construction & Finishing", value: 5456000 },
  { n: 16, project: "Hoffaz International Academy, Amman", client: "Hoffaz International Academy", role: "Main Contractor", date: "Jan 2016", year: 2016, desc: "Construction & Finishing", value: 344463 },
  { n: 17, project: "Al Muraba'a Al Sehhi, Ma'an", client: "Khayrat Belady Company", role: "Main Contractor", date: "Jun 2016", year: 2016, desc: "Construction & Finishing", value: 2768000 },
  { n: 18, project: "Ahmad 1 Apartments", client: "Hawari Housing Company", role: "Main Contractor", date: "Nov 2016", year: 2016, desc: "Construction & Finishing", value: 560000 },
  { n: 19, project: "Amman Arab University", client: "Amman Arab University", role: "Main Contractor", date: "Dec 2016", year: 2016, desc: "Construction & Finishing", value: 870818 },
  { n: 20, project: "Sameh Mall Market, Jerash", client: "Sameh Mall Group", role: "Main Contractor", date: "Jan 2017", year: 2017, desc: "Construction & Finishing", value: 933955 },
  { n: 21, project: "Yusra Center Building, Amman", client: "Ms. Hurricane Investment Company", role: "Main Contractor", date: "Sep 2017", year: 2017, desc: "Construction & Finishing", value: 650000 },
  { n: 22, project: "Jawad Bakeries", client: "Mr. Nidal A. Snaineh", role: "Main Contractor", date: "Sep 2017", year: 2017, desc: "Construction & Finishing", value: 1250000 },
  { n: 23, project: "The Lobby Restaurant, Amman", client: "Mr. Mohammed Zain & Ms. Hawari Contracting Co.", role: "Main Contractor", date: "Mar 2018", year: 2018, desc: "Construction & Finishing", value: 441975 },
  { n: 24, project: "Sameh Mall Market", client: "Kama Investment", role: "Main Contractor", date: "Jun 2018", year: 2018, desc: "Construction & Finishing", value: 3924940 },
  { n: 25, project: "Al Muraba'a Al Sehhi – Phase 2", client: "Khairat Belady Investment", role: "Main Contractor", date: "Nov 2018", year: 2018, desc: "Construction & Finishing", value: 2400000 },
  { n: 26, project: "Nancy Complex 2", client: "Khalid Rabbabh & Shamsain Investment", role: "Main Contractor", date: "Jan 2019", year: 2019, desc: "Construction & Finishing", value: 5548687 },
  { n: 27, project: "Nancy Complex 1", client: "Khalid Rabbabh & Shamsain Investment", role: "Main Contractor", date: "Mar 2019", year: 2019, desc: "Construction & Finishing", value: 1856000 },
  { n: 28, project: "Al Mafraq Complex", client: "Mafraq Hall for Wedding & Events Company", role: "Main Contractor", date: "Jul 2019", year: 2019, desc: "Construction & Finishing", value: 990000 },
  { n: 29, project: "KAREEM Hypermarket", client: "Mr. Khalid Rabbah", role: "Main Contractor", date: "Aug 2019", year: 2019, desc: "Construction & Finishing", value: 1450000 },
  { n: 30, project: "Sharaq Complex, Irbid", client: "Mr. Husam Subhi", role: "Main Contractor", date: "Jul 2020", year: 2020, desc: "Construction & Finishing", value: 572000 },
  { n: 31, project: "Admission and Administration Unit", client: "University of Petra", role: "Renovation", date: "Aug 2020", year: 2020, desc: "Construction & Finishing", value: 107144 },
  { n: 32, project: "Faculty of Arts and Science", client: "University of Petra", role: "Renovation", date: "Aug 2020", year: 2020, desc: "Construction & Finishing", value: 70000 },
  { n: 33, project: "Project Girls Housing Building", client: "University of Petra", role: "Renovation", date: "Nov 2020", year: 2020, desc: "Construction & Finishing", value: 77000 },
  { n: 34, project: "Public Transportation – Depot Phase I", client: "Jordan Turkish Company for Operating", role: "Main Contractor", date: "Nov 2020", year: 2020, desc: "Construction & Finishing", value: 120000 },
  { n: 35, project: "Sameh Mall, Russeifa, Zarqa", client: "Sameh Mall Group and Mr. Tariq Hijazi", role: "Main Contractor", date: "Nov 2020", year: 2020, desc: "Construction & Finishing", value: 600000 },
  { n: 36, project: "Farah International Bakery, Marka, Amman", client: "Mr. Abdul Khalifeh Assaf", role: "Main Contractor", date: "Mar 2021", year: 2021, desc: "Construction & Finishing", value: 120000 },
  { n: 37, project: "Tariq Hijazi & Partner Complex, Khaleda, Amman", client: "Mr. Tariq Hijazi", role: "Main Contractor", date: "Jun 2020", year: 2020, desc: "Construction & Finishing", value: 700000 },
  { n: 38, project: "Mumtalkat School, Amman Airport Road", client: "Mumtalkat Investment Company", role: "Main Contractor", date: "Jul 2020", year: 2020, desc: "Construction & Finishing", value: 2150000 },
  { n: 39, project: "Officers & Administration Buildings, Marka, Amman", client: "Royal Jordanian Air Force", role: "Main Contractor", date: "Mar 2021", year: 2021, desc: "Construction & Finishing", value: 587341 },
  { n: 40, project: "Dental College Building – Phase I, Amman Airport Road", client: "University of Petra", role: "Main Contractor", date: "Mar 2022", year: 2022, desc: "Construction & Finishing", value: 1664811 },
  { n: 41, project: "Dabouq Village, Amman", client: "Mr. Eyad Samir Elioeh", role: "Main Contractor", date: "May 2022", year: 2022, desc: "Construction & Finishing", value: 616500 },
  { n: 42, project: "Chief Families Apartment Building, Marka, Amman", client: "Royal Jordanian Air Force", role: "Main Contractor", date: "May 2022", year: 2022, desc: "Construction & Finishing", value: 1650000 },
  { n: 43, project: "Staff Residence for the Royal Air Force Commander", client: "Royal Jordanian Air Force", role: "Main Contractor", date: "May 2022", year: 2022, desc: "Construction & Finishing", value: 249500 },
  { n: 44, project: "Bait Ras School, Irbid", client: "Ministry of Education", role: "Main Contractor", date: "Jun 2022", year: 2022, desc: "Construction & Finishing", value: 2431580 },
  { n: 45, project: "Dental College Building, Salt", client: "Amman Al Ahliyya University", role: "Main Contractor", date: "Jun 2022", year: 2022, desc: "Construction & Finishing", value: 1480000 },
  { n: 46, project: "AbdulHadi Hospital Extension Structure Works", client: "AbdulHadi Hospital", role: "Main Contractor", date: "Aug 2022", year: 2022, desc: "Construction & Finishing", value: 1950000 },
  { n: 47, project: "Middle East University Classroom Buildings", client: "Middle East University", role: "Main Contractor", date: "Dec 2022", year: 2022, desc: "Construction & Finishing", value: 350000 },
  { n: 48, project: "Middle East University Scientific Colleges", client: "Middle East University", role: "Main Contractor", date: "Dec 2022", year: 2022, desc: "Civil Works", value: 199997 },
  { n: 49, project: "UK VAC & Visa Barakeh Mall", client: "Global Amman For Admin Services LLC", role: "Main Contractor", date: "Aug 2024", year: 2024, desc: "Construction & Finishing", value: 286128.54 },
  { n: 50, project: "Taqarob School, Irbid", client: "National Community Colleges Foundation Company", role: "Main Contractor", date: "Jun 2025", year: 2025, desc: "Construction", value: 271000 }
];
